name: Test Project

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Run tests
      run: xcodebuild clean test -project "ReCombine-Scoreboard-SwiftUI.xcodeproj" -scheme "ReCombine-Scoreboard-SwiftUI" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
    - name: Build App
      run: xcodebuild -project "ReCombine-Scoreboard-SwiftUI.xcodeproj" -scheme "ReCombine-Scoreboard-SwiftUI" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
